[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash==4.4.1",
    "dash-bootstrap-components==2.0.4",
    "gunicorn==21.2.0",
    "pandas==2.1.4",
    "plotly==6.9.0",
    "requests==2.31.0",
]

[tool.ruff]
line-length = 100
indent-width = 4

[tool.ruff.format]
quote-style = "single"

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
