FROM node:22-slim

RUN npm install -g corepack  && \
    corepack prepare yarn@stable --activate

WORKDIR /react-app
COPY ./client/package.json /react-app

RUN yarn install

COPY ./client/craco.config.js /react-app/
COPY ./client/src /react-app/src
COPY ./client/public /react-app/public

CMD ["yarn", "start"]
