---
version: "3"

services:
    mongo-db:
        image: mongo:8.0-rc
        volumes:
            - ./data:/data/db
    react-frontend:
        build:
            context: ./
            dockerfile: ./Dockerfile-react
        depends_on:
            - mongo-db
        ports:
            - 3000:3000
    django-backend:
        build:
            context: ./
            dockerfile: ./Dockerfile-django
        depends_on:
            - mongo-db
            - react-frontend
        ports:
            - 8000:8000
...
