FROM python:3.12

RUN pip install "poetry==1.8.3"

ADD https://api.github.com/repos/TACC/PandemicExerciseSimulator/git/refs/heads/main /version.json
RUN git clone --branch 0.2.2 https://github.com/TACC/PandemicExerciseSimulator /PES
WORKDIR /PES

RUN poetry config virtualenvs.create false && \
    poetry install --no-root

WORKDIR /django-app
COPY ./backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ./backend/pet /django-app/pet

CMD ["celery", "-A", "pet.pes_task", "worker", "--loglevel=INFO"]
