# Generated by Django 5.0.3 on 2024-08-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('reproduction_number', models.FloatField()),
                ('beta_scale', models.FloatField()),
                ('tau', models.FloatField()),
                ('kappa', models.FloatField()),
                ('gamma', models.FloatField()),
                ('chi', models.FloatField()),
                ('rho', models.FloatField()),
                ('nu', models.CharField(choices=[('high', 'high'), ('low', 'low')], max_length=4)),
                ('vaccine_wastage_factor', models.IntegerField()),
                ('antiviral_effectiveness', models.IntegerField()),
                ('antiviral_wastage_factor', models.IntegerField()),
            ],
        ),
    ]
