# Generated by Django 5.0.3 on 2024-08-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('R0', models.FloatField()),
                ('beta_scale', models.FloatField()),
                ('tau', models.FloatField()),
                ('kappa', models.FloatField()),
                ('gamma', models.FloatField()),
                ('chi', models.FloatField()),
                ('rho', models.FloatField()),
                ('nu', models.CharField(choices=[('high', 'high'), ('low', 'low')], max_length=4)),
                ('initial_infected', models.TextField(null=True)),
                ('phas', models.TextField(null=True)),
                ('antiviral_effectiveness', models.FloatField(null=True)),
                ('antiviral_wastage_factor', models.FloatField(null=True)),
                ('antiviral_stockpile', models.TextField(null=True)),
                ('vaccine_wastage_factor', models.FloatField(blank=True, default=None, null=True)),
                ('vaccine_pro_rata', models.CharField(choices=[('children', 'children'), ('pro_rata', 'pro_rata')], max_length=8, null=True)),
                ('vaccine_adherence', models.TextField(null=True)),
                ('vaccine_effectiveness', models.TextField(null=True)),
                ('vaccine_stockpile', models.TextField(null=True)),
            ],
        ),
    ]
