# Generated by Django 5.0.9 on 2026-01-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='state',
            field=models.TextField(default='Texas'),
            preserve_default=False,
        ),
    ]
