# Generated by Django 5.0.3 on 2024-08-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccine_wastage_factor',
            field=models.FloatField(null=True),
        ),
    ]
