# Generated by Django 5.0.3 on 2024-08-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='antiviral_effectiveness',
            field=models.FloatField(),
        ),
    ]
