# Generated by Django 5.0.9 on 2026-01-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='model_type',
            field=models.TextField(default='seatird-stochastic'),
            preserve_default=False,
        ),
    ]
