# Generated by Django 5.0.3 on 2024-10-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_pet_vaccine_wastage_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nu',
            field=models.TextField(),
        ),
    ]
