# Generated by Django 5.0.9 on 2026-01-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pet_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='immune_period',
            field=models.FloatField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='infectious_period',
            field=models.FloatField(default=14),
            preserve_default=False,
        ),
    ]
