# Generated by Django 5.0.3 on 2024-10-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_nu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='phas',
            new_name='npis',
        ),
    ]
