# Generated by Django 5.0.9 on 2026-02-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_pet_immune_period_pet_infectious_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='antiviral_effectiveness',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='antiviral_stockpile',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='antiviral_wastage_factor',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vaccine_pro_rata',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vaccine_wastage_factor',
        ),
        migrations.AddField(
            model_name='pet',
            name='sigma',
            field=models.TextField(default='[1,1,1,1,1]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccine_capacity',
            field=models.FloatField(blank=True, default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccine_effectiveness_lag',
            field=models.FloatField(blank=True, default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccine_model',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccine_priority_groups',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccine_adherence',
            field=models.TextField(blank=True, default='[1,1,1,1,1]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccine_effectiveness',
            field=models.TextField(blank=True, default='[1,1,1,1,1]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccine_stockpile',
            field=models.TextField(blank=True, default='[{"id":0,"day":22,"amount",22}]'),
            preserve_default=False,
        ),
    ]
