# Generated by Django 5.0.9 on 2026-02-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_remove_pet_antiviral_effectiveness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccine_adherence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccine_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccine_effectiveness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccine_effectiveness_lag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccine_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccine_priority_groups',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccine_stockpile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
